[workspace]
members = [
    "crates/mlx-lm",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }

[package]
name = "mlx-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "generate"
path = "src/bin/generate.rs"

[[bin]]
name = "mlx-server"
path = "src/bin/mlx-server.rs"

[dependencies]
mlx-lm = { path = "crates/mlx-lm" }
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { version = "1", features = ["rt", "macros"] }
